### PR TITLE
Adding ephemeral patches for 14.0.3 - 15.0.2

### PR DESCRIPTION
**Pull request by eric-young**
ephemeral driver patches for Nova Newton (14.0.3, 14.0.4, 14.0.5) and Ocata (15.0.0, 15.0.1, and 15.0.2). Tested by running tempest tests for both nova and cinder

### CODE REVIEW

**Comment by jtwill98** [comment]
Looks, good who can merge these?

**Comment by eric-young** [comment]
Thanks John.

I'm the maintainer for the ScaleIO cinder driver, and have made sure that the Tempest tests pass with the patches.

If it makes it easier in the future, I can be added as a maintainer of the repo and perform my own merges.

Eric
github.com/eric-young



Sent via the Samsung Galaxy S® 6, an AT&T 4G LTE smartphone


-------- Original message --------

**Comment by jtwill98** [comment]
BTW, I pulled your PR and tested 14.03 and it patched successfully.

**Comment by eric-young** [comment]
Found an issue with the patch for nova 14.0.3, which has been resolved

**Pull request merged**
